export const teamConstants = {
   TEAM_SET_NAME: "TEAM_SET_NAME",
    TEAM_APPLIED:"TEAM_APPLIED",
    TEAM_DECLINED:"TEAM_DECLINED",
    TEAM_CURRENT_QUESTION: "TEAM_CURRENT_QUESTION",
    TEAM_GIVEN_ANSWER: "TEAM_GIVEN_ANSWER",
    TEAM_INCREASE_SCORE_SCORE: "TEAM_INCREASE_SCORE"
};

export const questionConstants = {
    QUESTION_RECEIVED: "QUESTION_RECEIVED",
    QUESTION_CLOSED:"QUESTION_CLOSED"
};

export const answerConstants = {
    APPLY_ANSWER:"APPLY_ANSWER",
    APPLIED_ANSWER:"APPLIED_ANSWER",
    CHANGE_ANSWER:"CHANGE_ANSWER",
    CHANGED_ANSWER:"CHANGED_ANSWER",
    RESET_ANSWER:"RESET_ANSWER"
}

