export const categoryConstants = {
    CATEGORIES_GET_PENDING: 'CATEGORIES_GET_PENDING',
    CATEGORIES_GET_SUCCESS: 'CATEGORIES_GET_SUCCESS',
    CATEGORIES_GET_ERROR: 'CATEGORIES_GET_ERROR'
};

export const questionsConstants = {
    QUESTIONS_GET_PENDING: 'QUESTIONS_GET_PENDING',
    QUESTIONS_GET_SUCCESS: 'QUESTIONS_GET_SUCCESS',
    QUESTIONS_GET_ERROR: 'QUESTIONS_GET_ERROR'
};
