export const categoryConstants = {
    CATEGORIES_GET_PENDING: 'CATEGORIES_GET_PENDING',
    CATEGORIES_GET_SUCCESS: 'CATEGORIES_GET_SUCCESS',
    CATEGORIES_GET_ERROR: 'CATEGORIES_GET_ERROR'
};

export const questionsConstants = {
    QUESTIONS_GET_PENDING: 'QUESTIONS_GET_PENDING',
    QUESTIONS_GET_SUCCESS: 'QUESTIONS_GET_SUCCESS',
    QUESTIONS_GET_ERROR: 'QUESTIONS_GET_ERROR',
    SELECT_QUESTION:"SELECT_QUESTION",
    QUESTION_ROUND_STARTED:"QUESTION_ROUND_STARTED",
    QUESTIONS_REMOVE_QUESTION: "QUESTIONS_REMOVE_QUESTION"
};

export const answerConstants = {
    ANSWER_SENT: 'ANSWER_SENT'
};

export const roundConstants = {
    ROUND_ADD_CATEGORIES: 'ROUND_ADD_CATEGORIES'
};

export const teamConstants = {
    TEAM_SET_GIVEN_ANSWER: "TEAM_SET_GIVEN_ANSWER",
    TEAM_INCREASE_SCORE: "TEAM_INCREASE_SCORE"
};